service:
  name: lightsail-snapshots

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 256
  region: ap-southeast-2
  logRetentionInDays: 14
  environment:
    # BACKUP_INSTANCES: 'instance1,instance2'
    # BACKUP_DAYS: 7
    # BACKUP_WEEKS: 12
    # BACKUP_MONTHS: 12
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "lightsail:CreateInstanceSnapshot"
        - "lightsail:DeleteInstanceSnapshot"
        - "lightsail:GetInstanceSnapshot"
        - "lightsail:GetInstanceSnapshots"
        - "lightsail:GetInstances"
      Resource:
        - "*"

package:
  exclude:
    - "**/**.test.*"

functions:
  backup:
    handler: src/index.handler
    events:
      - schedule: cron(0 16 * * ? *) # 2am Melbourne Time = 16:00 UTC
